### PR TITLE
Require ember 4.8+ and test-helpers 3.x

### LINKED ISSUE #1977: Issue added by version 5.0.0
When you update from version 4.x to 5.0.0 using Ember.js 5 you'll see a weird issue in the acceptance tests that use `setFlatpickrDate` helper

image

### PR DESCRIPTION
**Pull request by AmauryD**
Resolves #1977

### CODE REVIEW

**Comment by RobbieTheWagner** [comment]
@AmauryD it looks like we probably need to run ember-cli-update as well and drop support for Ember < 4.8 to make this work.

**Comment by AmauryD** [comment]
@RobbieTheWagner Job's done ! 
I also updated the peerDeps string to only allow ember-source > 4.8 https://github.com/RobbieTheWagner/ember-flatpickr/pull/2036/commits/cf95301bf55822d0d4eddbe240ce915a8df4eb71

**Review by RobbieTheWagner — APPROVED** [review]
LGTM! Thanks for the PR 😄

**Comment by RobbieTheWagner** [comment]
@AmauryD looks like there are some conflicts. Once those are resolved, we can merge.

**Pull request merged**
